/* This file was generated by the Hex-Rays decompiler version 8.2.0.221215.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 __fastcall sub_4004A0(); // weak
// int puts(const char *s);
// size_t strlen(const char *s);
// int __fastcall __libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int fprintf(FILE *stream, const char *format, ...);
// __int64 _gmon_start__(void); weak
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
signed __int64 deregister_tm_clones();
__int64 register_tm_clones();
signed __int64 _do_global_dtors_aux();
__int64 frame_dummy();
__int64 __fastcall check_password(const char *a1);
int __cdecl main(int argc, const char **argv, const char **envp);
void _libc_csu_fini(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_601010)(void) = NULL; // weak
_UNKNOWN _bss_start; // weak
_UNKNOWN unk_60104F; // weak
FILE *stderr; // idb
char completed_7585; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (0000000000400480) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    return (void *)_gmon_start__();
  return result;
}
// 4004F0: using guessed type __int64 _gmon_start__(void);

//----- (00000000004004A0) ----------------------------------------------------
__int64 sub_4004A0()
{
  return qword_601010();
}
// 4004A0: using guessed type __int64 __fastcall sub_4004A0();
// 601010: using guessed type __int64 (*qword_601010)(void);

//----- (0000000000400500) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  __libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v4,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    _libc_csu_fini,
    a3,
    &v5);
  __halt();
}
// 400506: positive sp value 8 has been found
// 40050D: variable 'v3' is possibly undefined

//----- (0000000000400530) ----------------------------------------------------
signed __int64 deregister_tm_clones()
{
  signed __int64 result; // rax

  result = &unk_60104F - &_bss_start;
  if ( (unsigned __int64)(&unk_60104F - &_bss_start) > 0xE )
    return 0LL;
  return result;
}

//----- (0000000000400570) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (00000000004005B0) ----------------------------------------------------
signed __int64 _do_global_dtors_aux()
{
  signed __int64 result; // rax

  if ( !completed_7585 )
  {
    result = deregister_tm_clones();
    completed_7585 = 1;
  }
  return result;
}
// 601068: using guessed type char completed_7585;

//----- (00000000004005D0) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 4005D0: could not find valid save-restore pair for rbp

//----- (00000000004005F6) ----------------------------------------------------
__int64 __fastcall check_password(const char *a1)
{
  unsigned __int8 i; // [rsp+1Ah] [rbp-6h]

  if ( strlen(a1) != 4 )
    return 0LL;
  for ( i = 0; i <= 3u; ++i )
  {
    if ( (unsigned __int8)a1[i] != (unsigned __int8)(0x46C6F48u >> (8 * i)) )
      return 0LL;
  }
  return 1LL;
}

//----- (0000000000400675) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  if ( argc == 2 )
  {
    if ( (unsigned int)check_password(argv[1]) == 1 )
    {
      puts("Congratulations!");
      return 0;
    }
    else
    {
      puts("ko");
      return 1;
    }
  }
  else
  {
    fprintf(stderr, "Usage: %s password\n", *argv);
    return 1;
  }
}

//----- (00000000004006F0) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v3; // rbp
  __int64 i; // rbx

  v3 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v3 )
  {
    for ( i = 0LL; i != v3; ++i )
      _frame_dummy_init_array_entry[i]();
  }
}
// 600E10: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 600E18: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000400764) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=22 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
