// tmpj8ekhw4v_text.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

// 0000000000400500: void _start(Register (ptr64 Eq_9) rdx, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
void _start(void (* rdx)(), word32 dwArg00, char * ptrArg08)
{
	void * fp;
	word64 qwArg00;
	__align_stack<word64>(&ptrArg08);
	__libc_start_main(&g_t400675, (int32) qwArg00, &ptrArg08, &g_t4006F0, &g_t400760, rdx, fp);
	__halt();
}

// 0000000000400530: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (false || true)
		return;
	null();
}

// 0000000000400570: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	if (true || true)
		return;
	null();
}

// 00000000004005B0: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b601068 == 0x00)
	{
		deregister_tm_clones();
		g_b601068 = 0x01;
	}
}

// 00000000004005D0: void frame_dummy()
void frame_dummy()
{
	if (g_qw600E20 != 0x00 && false)
	{
		fn0000000000000000();
		register_tm_clones();
	}
	else
		register_tm_clones();
}

// 00000000004005F6: Register word32 check_password(Register (ptr64 Eq_67) rdi)
// Called from:
//      main
word32 check_password(union Eq_67 * rdi)
{
	uint64 rax_69;
	if (strlen(rdi) != 0x04)
		rax_69 = 0x00;
	else
	{
		cu8 bLoc0E_83;
		for (bLoc0E_83 = 0x00; bLoc0E_83 <= 0x03; ++bLoc0E_83)
		{
			if ((word32) *((char *) rdi + (uint64) bLoc0E_83) != (0x046C6F48 >> (bLoc0E_83 << 0x03) & 0xFF))
			{
				rax_69 = 0x00;
				return (word32) rax_69;
			}
		}
		rax_69 = 0x01;
	}
	return (word32) rax_69;
}

// 0000000000400675: void main(Register (ptr64 Eq_96) rsi, Register word32 edi)
void main(struct Eq_96 * rsi, word32 edi)
{
	if (edi != 0x02)
		fprintf(stderr, "Usage: %s password\n", rsi->ptr0000);
	else if (check_password(rsi->ptr0008) == 0x01)
		puts("Congratulations!");
	else
		puts("ko");
}

// 00000000004006F0: void __libc_csu_init(Register word64 rdx, Register word64 rsi, Register word32 edi)
void __libc_csu_init(word64 rdx, word64 rsi, word32 edi)
{
	word64 rdi;
	word32 edi = (word32) rdi;
	_init();
	int64 rbp_31 = 0x00600E18 - 0x00600E10;
	if (rbp_31 >> 0x03 != 0x00)
	{
		Eq_144 rbx_45 = 0x00;
		do
		{
			(*((char *) g_a600E10 + rbx_45 * 0x08))();
			rbx_45 = (word64) rbx_45.u1 + 1;
		} while (rbx_45 != rbp_31 >> 0x03);
	}
}

// 0000000000400760: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// tmpj8ekhw4v_jcr.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

word64 g_qw600E20 = 0x00; // 0000000000600E20
// tmpj8ekhw4v_plt.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

<anonymous> g_t4004B6 = <code>; // 00000000004004B6
<anonymous> g_t4004C6 = <code>; // 00000000004004C6
<anonymous> g_t4004D6 = <code>; // 00000000004004D6
<anonymous> g_t4004E6 = <code>; // 00000000004004E6
// tmpj8ekhw4v_fini.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

// 0000000000400764: void _fini()
void _fini()
{
}

// tmpj8ekhw4v_rodata.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

char g_str400774[] = "Usage: %s password\n"; // 0000000000400774
char g_str400788[] = "Congratulations!"; // 0000000000400788
char g_str400799[] = "ko"; // 0000000000400799
// tmpj8ekhw4v_got.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

<anonymous> * __gmon_start___GOT = null; // 0000000000600FF8
// tmpj8ekhw4v_got_plt.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

<anonymous> * puts_GOT = &g_t4004B6; // 0000000000601018
<anonymous> * strlen_GOT = &g_t4004C6; // 0000000000601020
<anonymous> * __libc_start_main_GOT = &g_t4004D6; // 0000000000601028
<anonymous> * fprintf_GOT = &g_t4004E6; // 0000000000601030
// tmpj8ekhw4v_init_array.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

<anonymous> * g_a600E10[] = // 0000000000600E10
	{
	};
// tmpj8ekhw4v_init.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

// 0000000000400480: void _init()
// Called from:
//      __libc_csu_init
void _init()
{
	if (__gmon_start__ != 0x00)
		__gmon_start__();
}

// tmpj8ekhw4v_bss.c
// Generated by decompiling tmpj8ekhw4v
// using Reko decompiler version 0.11.2.0.

#include "tmpj8ekhw4v.h"

FILE * stderr = &g_tC020C0; // 0000000000601060
byte g_b601068 = 0x00; // 0000000000601068
