//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t check_password(int64_t str);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x601060

// ------------------------ Functions -------------------------

// Address range: 0x4005f6 - 0x400675
int64_t check_password(int64_t str) {
    // 0x4005f6
    if (strlen((char *)str) != 4) {
        // 0x400673
        return 0;
    }
    int32_t v1 = 0; // 0x400612
    char v2 = *(char *)((int64_t)(v1 % 256) + str); // 0x400637
    int64_t result = 0; // 0x400655
    while (v2 == (char)(0x46c6f48 >> (8 * v1 & 24))) {
        // 0x40065e
        v1 = 0x1000000 * v1 + 0x1000000 >> 24;
        result = 1;
        if ((char)v1 >= 4) {
            // break -> 0x400673
            break;
        }
        v2 = *(char *)((int64_t)(v1 % 256) + str);
        result = 0;
    }
    // 0x400673
    return result;
}

// Address range: 0x400675 - 0x4006ef
int main(int argc, char ** argv) {
    if ((int32_t)argc != 2) {
        // 0x40068a
        fprintf(g1, "Usage: %s password\n", argv);
        // 0x4006ed
        return 1;
    }
    // 0x4006b1
    int64_t result; // 0x400675
    if ((int32_t)check_password(*(int64_t *)((int64_t)argv + 8)) != 1) {
        // 0x4006de
        puts("ko");
        result = 1;
    } else {
        // 0x4006cd
        puts("Congratulations!");
        result = 0;
    }
    // 0x4006ed
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 2

